apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2 # Specify the number of replicas
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: adityaojhalang/flask-app:v2 # Replace with your Docker Hub image
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: FLASK_ENV
              value: "development"
            - name: MONGO_HOST
              value: "mongodb"
  strategy: # 'strategy' should be at the same level as 'selector' and 'template'
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
